name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build-android:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "latest"